# Generated by Django 2.2.7 on 2019-11-15 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sports_weight',
            new_name='sports_type_weight',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sports',
        ),
        migrations.AddField(
            model_name='student',
            name='sports_type',
            field=models.ManyToManyField(to='students.Sports', verbose_name='运动'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dormitory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Dormitory', verbose_name='宿舍号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='games_type',
            field=models.ManyToManyField(to='students.Games', verbose_name='游戏类型'),
        ),
        migrations.AlterField(
            model_name='student',
            name='novels_type',
            field=models.ManyToManyField(to='students.Novels', verbose_name='小说类型'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.School', verbose_name='学校名称'),
        ),
        migrations.AlterField(
            model_name='student',
            name='videos_type',
            field=models.ManyToManyField(to='students.Videos', verbose_name='看剧类型'),
        ),
    ]
