# Generated by Django 2.2.7 on 2019-11-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20191115_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='games_type',
            field=models.ManyToManyField(blank=True, to='students.Games', verbose_name='游戏类型'),
        ),
        migrations.AlterField(
            model_name='student',
            name='novels_type',
            field=models.ManyToManyField(blank=True, to='students.Novels', verbose_name='小说类型'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sleep_time',
            field=models.IntegerField(blank=True, choices=[(1, '21:00之前'), (2, '21:01-22:00'), (3, '22:01-23:00'), (4, '23:01-23:59'), (5, '24:00之后')], null=True, verbose_name='睡觉时间'),
        ),
        migrations.AlterField(
            model_name='student',
            name='smoke',
            field=models.BooleanField(choices=[(False, '不吸烟'), (True, '吸烟')], null=True, verbose_name='吸烟'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sports_type',
            field=models.ManyToManyField(blank=True, to='students.Sports', verbose_name='运动'),
        ),
        migrations.AlterField(
            model_name='student',
            name='videos_type',
            field=models.ManyToManyField(blank=True, to='students.Videos', verbose_name='看剧类型'),
        ),
        migrations.AlterField(
            model_name='student',
            name='wake_time',
            field=models.IntegerField(blank=True, choices=[(1, '7:00之前'), (2, '7:01-8:00'), (3, '8:01-9:00'), (4, '9:01-10:00'), (5, '10:01之后')], null=True, verbose_name='起床时间'),
        ),
    ]
