# Generated by Django 2.2.7 on 2019-11-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20191115_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_super',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='超级管理员'),
        ),
    ]
